server:
  port: 8012
  forward-headers-strategy: NATIVE
spring:
  thymeleaf:
    cache: false
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWD}
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  type-aliases-package: com.atlxc.VulnScan.product.entity
  mapper-locations:
    - classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
init:
  file:
    path: ./init.flag
api:
  url: ${API_URL}
  key: ${API_KEY}