server:
  port: 80
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/vulnscan?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis-plus:
  mapper-locations:
    - classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
